### ISSUE TITLE
Paintomics 4 servers

### ISSUE THREAD

**Issue by ChiaraAnsermino** [ConesaLab/paintomics4#4]
Hello,
I'm trying to access PaintOmics from my internet browser but it gives me the errors "the site can't be reached" and  "www.paintomics.org refused to connect".
There's any server issue?

**Comment by TianYuan-Liu** [comment]
Thank you for reaching out and bringing this to our attention. I apologize for the inconvenience you're experiencing. We are currently looking into the issue with our server and are committed to resolving it as soon as possible. I'll make sure this is addressed this week and will keep you updated on our progress.

**Comment by TianYuan-Liu** [comment]
Hi, currently, I'm unable to access our server to diagnose the problem directly. I plan to work on resolving this issue first thing next Monday when I can get in touch with our technician. In the meantime, you can use the previous version of PaintOmics available at http://188.166.42.44/. We appreciate your patience and understanding as we work to restore full access to the service

> Hello, I'm trying to access PaintOmics from my internet browser but it gives me the errors "the site can't be reached" and "www.paintomics.org refused to connect". There's any server issue?

**Comment by TianYuan-Liu** [comment]
Hi Chiara, 

I wanted to inform you that Paintomics4 is now available at paintomics.uv.es. We are currently reinstalling all the species, but we will do it faster this time. Please let me know which species you are currently working on, so we can prioritize its reinstallation. 

I apologize for the inconvenience caused by the server accident that occurred earlier, which required us to reinstall everything. 

Thank you for your patience and understanding.

**Comment by ChiaraAnsermino** [comment]
Hi,
Thank you for solving the issue. 
I’m currently working with metabolomics and proteomics samples from human patients.

Thank you again!

**Comment by TianYuan-Liu** [comment]
Hi Chiara, I've successfully installed Human with both Reactome and KEGG integrations. If you encounter any issues while using it, please let me know. Thanks!
